# 1. Algebra con Python

## 1.1. Intro

El álgebra lineal es la rama de las matemáticas que trata las ecuaciones y funciones lineales, y sus representaciones a través de matrices y espacios vectoriales. Nos ayuda a comprender términos geométricos en dimensiones superiores y a realizar operaciones matemáticas con ellos. Por definición, el álgebra trata principalmente con escalares (entidades unidimensionales), pero el álgebra lineal tiene vectores y matrices (entidades que poseen dos o más componentes dimensionales) para tratar con ecuaciones y funciones lineales.

El álgebra lineal es el corazón de casi todas las áreas de las matemáticas como la geometría y el análisis funcional. Sus conceptos son un requisito previo crucial para comprender la teoría detrás de la ciencia de datos. El científico de datos no necesita comprender el álgebra lineal antes de comenzar con la ciencia de datos, pero en algún momento es necesario comprender cómo funcionan realmente los diferentes algoritmos.

Para trabajar con álgebra en Python se utiliza el módulo `NumPy`, que es una biblioteca que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas.

In [24]:
import numpy as np

## 1.2. Elementos del álgebra lineal

Existen diferentes tipos de objetos o estructuras dentro del algebra lineal:

- Escalar: número
- Vector: lista de números
- Matrix: lista bidimensional de números
- Tensor: lista n-dimensional de números, donde n > 2

En `numpy` a las listas se le denomina *array*:

<img src="_images\numpy_array_dimensions.png" alt="Drawing" style="width: 400px;"/>

Los arrays tienen una característica muy especial y es que se encuentran referenciados en la memoria. Esto ocurre porque numpy hace una gestión óptima de la memoria y no va a malgastarla creando copias por valor. Para crear una copia real de un array y no modificar el original, tendremos que utilizar el método `.copy()`.

### 1.2.1. Escalares

Un escalar es únicamente un número, a diferencia de la mayoría de los otros elementos del álgebra lineal que son conjuntos de valores como los vectores y matrices. Generalmente, por convención a los escalares los escribimos en letra cursiva minúscula o usando el alfabeto griego.

Entre los principales conjuntos de escalares tenemos a:

- Números Naturales (ℕ): los números que se utilizan para contar los elementos de cualquier conjunto. (1, 2, 3, 4, …)
- Números Enteros (ℤ): el conjunto de los números enteros está dado por el conjunto de los naturales, sus negativos y el cero. (…, -2, -1, 0, 1, 2, …)
- Números Reales (ℝ): el conjunto de los reales incluye tanto a los racionales como a los irracionales.

### 1.2.2. Vectores

Un vector es un arreglo de números. Un vector $v$ de $n$ componentes se define como un conjunto ordenado de $n$ números escrito de la siguiente forma:

- vector fila:

\begin{align}
v = (v_1, v_2, \ldots, v_n)
\end{align}

- vector columna:

\begin{align}
v = \begin{bmatrix}v_1\\v_2\\\ldots\\v_n\end{bmatrix}
\end{align}

Se puede crear un vector mediante la función `array(list)` del módulo `NumPy`, y pasando como argumento una lista.

In [23]:
## Crear un vector de 5 elementos

v = np.array([8, 0, 3, 1, 5])

print(type(v))
print(v)

<class 'numpy.ndarray'>
[8 0 3 1 5]


In [19]:
print(v.shape)

(5,)


### 1.2.3. Matrices

Una matriz es un arreglo bi-dimensional de números. Cada elemento de la misma está identificado por dos índices, en lugar de uno como en los vectores. Usualmente, a una matriz la denotamos por una letra mayúscula en negrita.

\begin{align}
A = 
\begin{bmatrix}a_{11}&a_{12}&\ldots&a_{1j}&\ldots&a_{1n}\\
a_{21}&a_{22}&\ldots&a_{2j}&\ldots&a_{2n}\\
\vdots&\vdots& &\vdots& &\vdots\\
a_{i1}&a_{i2}&\ldots&a_{ij}&\ldots&a_{in}\\
\vdots&\vdots& &\vdots& &\vdots\\
a_{m1}&a_{m2}&\ldots&a_{mj}&\ldots&a_{mn}\end{bmatrix}\
\end{align}

Se puede crear un vector mediante la función `array(list)` del módulo `NumPy`, y pasando como argumento una lista de listas.

In [77]:
## Crear una matriz de 3x3

A = np.array([[5, 4, 7], [3, 8, 1], [1, 1, 1]])

print(type(A))
print(A)

<class 'numpy.ndarray'>
[[5 4 7]
 [3 8 1]
 [1 1 1]]


In [78]:
A = np.mat(A)
print(type(A))

<class 'numpy.matrix'>


In [79]:
print(A.shape)

(3, 3)


### 1.2.4. Tensores

Existen diversos casos en los cuales se precisan mas de dos ejes para almacenar valores. En el caso general, una matriz con un número regular de ejes se lo conoce como tensor.

Simplificando mucho, un tensor sería un cubo de datos si el número de dimensiones es de 3, si las dimensiones son superiores a este valor no se puede representar en el mundo físico. El concepto es difícil de imaginar, ya que nosotros únicamente percibimos 3 dimensiones, pero si lo entendemos como una ramificación en dónde por cada elemento ahora hay otra lista con dos elementos, entonces no es tan imposible hacernos una idea.

In [21]:
## Crear un tensor de 2x2x3

T = np.array([[[1, 2, 3], [5, 6, 7]],
              [[8, 9, 10], [11, 12, 13]]])

print(type(T))
print(T)

<class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]]]


In [20]:
print(T.shape)

(2, 2, 3)


## 1.3. Operaciones algebraicas

A continuación se muestran algunas de las operaciones algebraicas más útiles y frecuentes que se pueden realizar con vectores y matrices.

### 1.3.1. Operaciones con vectores

**Index y slicing:**

Al igual que con las listas, se puede extraer elementos de un vector en `numpy` del mismo modo.

In [49]:
v = np.array([1, 0, 1,])
v[0], v[-1], v[::-1]

(1, 1, array([1, 0, 1]))

**Multiplicación escalar:**

Consiste en multiplicar un vector $v$ por un escalar, el resultado es el de multiplicar cada elemento del vector por ese escalar.

In [25]:
v = np.array([8, 0, 3, 1, 5])
v*2

array([16,  0,  6,  2, 10])

**Suma de vectores:**

La suma o resta de vectores se realiza elemento a elemento (*element wise*). Para ello se emplean los símbolos habituales de adición y sustracción (`+/-`).

In [27]:
v = np.array([1, 0, 1,])
w = np.array([1, -2, 1,])

v + w

array([ 2, -2,  2])

In [28]:
v = np.array([1, 0, 1,])
w = np.array([1, -2, 1,])

v - w

array([0, 2, 0])

**Producto escalar:**

El producto escalar, o también conocido como *dot product*, consiste en multiplicar un vector por otro, el resultado es un escalar.

Para obtener el producto escalar de los vectores $v$ y $w$ se emplea la siguiente fórmula:

\begin{equation*}
v·w = \sum v_iw_i = |v||w|\cos\theta
\end{equation*}

En `numpy` se ejecuta mediante la función `np.dot(v1, v2)`.

In [26]:
v = np.array([1, 0, 1,])
w = np.array([1, -2, 1,])

np.dot(v, w)

2

### 1.3.2. Operaciones con matrices

**Index y slicing:**

Al igual que con las listas, se puede extraer elementos en `numpy` del mismo modo. Cuando se quiera realizar slicing en una matriz, al trabajar con dos dimensiones, se deben pasar dos argumentos separados por comas, siendo el primero de ellos el relativo a las filas y el segundo a las columnas.

In [50]:
## Index
A = np.array([[5, 4, 7], [3, 8, 1], [1, 1, 1]])
A[0], A[0][1]

(array([5, 4, 7]), 4)

In [52]:
## Slicing
A = np.array([[5, 4, 7], [3, 8, 1], [1, 1, 1]])
A[:2,:], A[-1, 1:]

(array([[5, 4, 7],
        [3, 8, 1]]),
 array([1, 1]))

**Matriz transpuesta:**

La matriz traspuesta de una matriz $A$ se denota por $A^T$, y se obtiene cambiando sus filas por columnas (o viceversa). La transpuesta de la traspuesta, es la matriz original.

$(A^T)^T = A$

Aunque es más dificil visualizarlo, también se puede transponer matrices de dimensiones supeiores 2.

In [80]:
A = np.random.randint(10, size = (5, 3))
type(A), A

(numpy.ndarray,
 array([[5, 3, 4],
        [7, 0, 5],
        [5, 5, 0],
        [0, 2, 0],
        [8, 2, 3]]))

In [81]:
type(A.T), A.T

(numpy.ndarray,
 array([[5, 7, 5, 0, 8],
        [3, 0, 5, 2, 2],
        [4, 5, 0, 0, 3]]))

In [82]:
type(A.T.T), A.T.T

(numpy.ndarray,
 array([[5, 3, 4],
        [7, 0, 5],
        [5, 5, 0],
        [0, 2, 0],
        [8, 2, 3]]))

**Matriz de ceros:**

Mediante el el comando `np.zeros()` se puede crear una matriz llena de ceros.

In [83]:
zero_matrix = np.zeros((3, 2))
type(zero_matrix), zero_matrix

(numpy.ndarray,
 array([[0., 0.],
        [0., 0.],
        [0., 0.]]))

**Matriz de unos:**

Mediante el el comando `np.ones()` se puede crear una matriz llena de unos.

In [56]:
ones_matrix = np.ones((3, 2))
ones_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

**Matriz identidad:**

La matriz identidad es aquella que tiene como elementos de su diagonal todo valores 1, y el resto de elementos valor 0. 

Para obtener una matriz identidad de dimensiones $n · n$ se utiliza el comando `np.identity(n)`, por defecto utiliza floats para cada elemento de la matriz, se pueden definir como enteros utilizando el argumento `dtype = int`.

In [36]:
I = np.identity(4, dtype = int)
I

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [35]:
I = np.eye(4, dtype = int)
I

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

Un aspecto importante de la matriz identidad, es que a pesar de que el producto de matrices no tiene propiedad conmutativa, la matriz identidad si que la tiene.

**Multiplicación por un escalar:**

Cuando multiplicamos un escalar por una matriz, cada uno de los elementos de la matriz es multiplicado por el escalar. Este tipo de producto cumple la propiedad conmutativa:

$\alpha·A = A·\alpha$

In [94]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

2*A, A*2

(array([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]),
 array([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]))

Esta operación produce el mismo resultado independientemente de que la matriz sea un objeto del tipo *np.matrix* o *np.ndarray*.

**Suma de matrices:**

Para poder sumar (o restar) dos matrices $A$ y $B$, éstas tienen que tener la misma dimensión puesto que la suma (o resta) se calcula sumando (o restando) los elementos de la misma posición.

Propiedades de la suma de matrices:

- Conmutativa: $A+B = B+A$
- Asociativa: $A+(B+C) = (A+B)+C$
- Distributiva escalar: $\alpha·(A+B) = \alpha·A + \alpha·B $

In [92]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

A + B, A - B

(array([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]),
 array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]))

**Producto escalar de matrices:**

También conocido como producto punto, es una operación un poco más compleja. Sean las matrices $A$ de dimensiones $mxn$, y $B$ de dimensiones $nxp$, el número de columnas de $A$ debe coincidier con el número de filas de $B$. Esto se debe a que el producto matricial se calcula como el producto escalar de las filas de la matriz $A$, por las columnas de $B$.

Propiedades del producto matricial:

- No conmutativo: $A+B \neq B+A$
- Asociativo: $A·(B·C)=(A·B)·C$
- Distributiva de la suma izquierda: $A·(B+A)=A·B+A·C$
- Distributiva de la suma derecha: $(A+B)·C=A·C+B·C$

In [100]:
A = np.array([[1, 2, 1], [2, -1, 0], [1, 0, 0]])
B = np.array([[1, 2, 3], [0, -1, 1], [3, -1, 0]])

A.dot(B), A*B

(array([[ 4, -1,  5],
        [ 2,  5,  5],
        [ 1,  2,  3]]),
 array([[1, 4, 3],
        [0, 1, 0],
        [3, 0, 0]]))

In [99]:
A = np.mat(np.array([[1, 2, 1], [2, -1, 0], [1, 0, 0]]))
B = np.mat(np.array([[1, 2, 3], [0, -1, 1], [3, -1, 0]]))

A.dot(B), A*B

(matrix([[ 4, -1,  5],
         [ 2,  5,  5],
         [ 1,  2,  3]]),
 matrix([[ 4, -1,  5],
         [ 2,  5,  5],
         [ 1,  2,  3]]))

Como se puede observar en los dos ejemplos, si utilizamos un objeto del tipo *np.ndarray* solo se podrá utilizar el método `.dot()`; mientras que si los objetos son del tipo *np.matrix* se podrá emplear tanto el método `.dot()` como `*`.

**Matriz inversa:**

La matriz inversa $A^{-1}$, de una matriz $A$, es aquella que verifica la expresión $AA^{-1} = A^{-1}A = I$.

La matriz inversa de $A$ es:

$A^{-1} = \frac{1}{|A|} adj (A)$

Donde $|A|$ es el determinante de $A$; y $adj(a)$, la matriz adjunta de $A$. De la expresión anterior podemos deducir que solamente tienen inversa las matrices cuadradas cuyo determinante es distinto de cero.

La inversa de una matriz en Python se puede obtener de dos formas:

- Mediante el método `.I`, es necesario que el tipo de objeto sea *np.matrix* y *np.ndarray*.
- Mediante la función `np.linalg.inv(A)`.

In [76]:
A = np.mat(np.array([[5, 4, 7], [3, 8, 1], [1, 1, 1]]))
A_inv = A.I
A_inv, A_inv*A

(matrix([[-0.875, -0.375,  6.5  ],
         [ 0.25 ,  0.25 , -2.   ],
         [ 0.625,  0.125, -3.5  ]]),
 matrix([[ 1.0000000e+00, -8.8817842e-16,  0.0000000e+00],
         [ 0.0000000e+00,  1.0000000e+00,  0.0000000e+00],
         [ 4.4408921e-16,  0.0000000e+00,  1.0000000e+00]]))

In [75]:
A = np.array([[5, 4, 7], [3, 8, 1], [1, 1, 1]])
A_inv = np.linalg.inv(A)
A_inv, A_inv.dot(A)

(array([[-0.875, -0.375,  6.5  ],
        [ 0.25 ,  0.25 , -2.   ],
        [ 0.625,  0.125, -3.5  ]]),
 array([[ 1.0000000e+00, -8.8817842e-16,  0.0000000e+00],
        [ 0.0000000e+00,  1.0000000e+00,  0.0000000e+00],
        [ 4.4408921e-16,  0.0000000e+00,  1.0000000e+00]]))

# 2. Estadística con Python

# X. Bibliografía

- Research Article: Linear Algebra – A Powerful Tool for Data Science. Hasheema Ishchi.
- https://numpy.org/